export { default as Main } from './Main'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as Contacts } from './Contacts'
export { default as Blog } from './Blog'